[package]
name = "qos_host"
version = "0.1.0"
edition = "2021"

[dependencies]
qos_core = { path = "../qos_core", default-features = false }

# Third party
axum = { version = "0.6.20", features = ["http1", "tokio"], default-features = false }
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"], default-features = false }
borsh = { version = "0.10" }

[features]
vm = ["qos_core/vm"]
