[package]
name = "qos_test_primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

# Override workspace lints for this test crate
[lints.rust]
missing_docs = "allow"
unsafe_code = "deny"

[lints.clippy]
missing_errors_doc = "allow"
module_name_repetitions = "allow"

[dependencies]
rand = { workspace = true }
nix = { workspace = true, default-features = false, features = ["signal"] }
