[package]
name = "qos_crypto"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = { version = "0.10", default-features = false }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
vsss-rs = { version = "4.3", default-features = false, features = ["std"] }


[dev-dependencies]
qos_hex = { path = "../qos_hex" }
