[package]
name = "eif_build"
version = "0.1.0"
publish = false

[dependencies]
sha2 = "0.9.5"
serde_json = "1.0"
clap = "3"
aws-nitro-enclaves-cose = "0.5"
aws-nitro-enclaves-image-format = "0.2.0"

[[bin]]
name = "eif_build"
path = "eif_build.rs"
